version: "3.3"

services:
  nginx:
    container_name: 'reverse-proxy'
    build:
      context: ./docker
      dockerfile: nginx.Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
    networks:
      - app
    restart: always

networks:
  app:
    driver: bridge
